### ISSUE TITLE
Frage: Quickedit für alle Post-Types möglich?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Plugin#10]
...ich ging bislang davon aus, dass es nicht geht, aber ich hab mich nie schlau gemacht. Kann man die Quick-Edit-Funktion für alle Inhaltstypen freischalten? Bzw. für für Medien? Bei letzteren wäre es immens hilfreich, denn man muss jedes olle Dok/Bild anklicken, nur um ein Schlagwort zu vergeben/löschen...

@xwolfde @rvdforst

**Comment by xwolfde** [comment]
Momentan zeltich nicht denkbar.
