### ISSUE TITLE
Assistent für einfacheres Ändern der Seitenreihenfolge 

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Plugin#7]
Mangels Rechten:
Labels Enhancement
Assignee xwolf

...besser spät als nie: Die Änderung der Seitenreihenfolge im Baum ist aktuell megaumständlich, (erzeugt evtl. sinnlose Revisionen, nicht getestet bislang) und verlangt das Anfassen jeder einzelnen Seite. Insbesondere beim Hinzufügen einer neuen Seite in einen bestehenden Baum muss man erstmal schauen, welche Zahlen als Gewichtung an den anderen Seiten vergeben wurden, denn Wordpress macht irgenwas dran - vielleicht dem Gesamtbaum folgend o.ä.?

Wie man das besser lösen könnte, weiß ich aktuell nicht genau Habe nur *hust* Joomal vor Augen mit der Seitenbaumliste und den kleinen Pfeilen zum Tauschen der Plätze. Man müsste mal bei Drupal gucken.

Was wir bisher tun bei Änderungen: Alle Seiten im betroffenen (Unter-)Baum öffnen und Zahlen in Zehnerschritten vergeben, um noch Platz für weitere Seiten zu lassen.

Zu Hülf! :sos:

**Comment by xwolfde** [comment]
(Was hat das mit dem Plugin zu tun? Was für ein Baum überhaupt? Accordion? Im Backend bei Seitenübersicht? Der Baum von dem Plugin Page Tree? Im Menü, wenn ja welches?)

Die Zahlen können gewählt werden wenn man ein Pagemenu aufruft, dies interessiert nur bei Pages mit Inlinenavigation.
Ich gehe davon aus, daß das damals so in Absicht so gelöst wurde. Damit hat man sich nun diesen Nachteil ins Haus geholt, dass man nun eben all diese schönen Funktionen die die menüverwaltung eigentlich hätte (eben das was du wolltest mit hoch und runterschieben) nicht nutzen kann und dafür die Nummerierung nutzen muss.

Es wäre zu überlegen, ob man diese doofe Lösung wieder wegmacht und stattdessen dort die richtige menunavi nutzt (bzw. die Obernavi in der die Seite ja gehört dann entsprechend ab der Position anzeigt und nicht wie jetzt die Page Navi.
Aber das ist dann mit Änderungsaufwand verbunden.
Einen einzigen Nachteil gibt es, btzw. einen Vorteil hat diese Lösung, die jetzt da ist:
Das Pagemenu muss nicht erst von einem Admin gemacht werden. Es wird selbstsständig gebaut eben aus den Seiten eines Bereiches. Das heisst es funktioniert sofort. Bei einem richtigen Menü müsste erst nachdem ein Redakteur die Seite fertig stellte, ein Admin diese Seite zu einem geeigneten Menü hinzufügen.

Eine andere Lösung, in den Pages die Menufunktion nachzubilden, die man bei normalen Menus hat statt die menüfunktion zu nutzen, ist sinnfrei.

TL;DR: Pest oder Cholera. Du kannst nicht beides haben: 
Entweder fesche Menüfunktionen: Dann muss der Admin mehr tun
Oder automatische Pages: Dann kann/muss der Autor/Redakteur eben wenn er die reihenfolge beeinflussen will eine Zahl 1-10 nutzen. (1-10 deswegen, weil aufkeiner Ebene einer Hierarchie mehr als 10 Elemente auftreten sollten).

**Comment by wrkb** [comment]
Auch hier wäre ein Telefonat/ein Jour-fixe besser. Das Thema ist ja kein Blocker, wir können es später besprechen.

Baum=Seitenbaum

Was meinst du mit Pagemenü und Obermenu?

Wenn ich die Reihenfolge von Seiten in der linken Navigation auf Inhaltsseiten ändern will, muss ich ALLE Seiten öffnen! Dass das totaler Humbug ist, liegt auf der Hand.

Jedes CMS hat hier Pfeile oder andere Hilfen (Javascript) zur Gewichtung von Seiten im Seitenbaum. Wordpress hat gar nichts dafür. --> Wordpress-spezifisches Problem, wurde nicht in Absicht so gelöst. Solange wir das Pagetreeview-Plugin hatten, war alles gut - das ist aber leider nicht mehr einsetzbar. Helfen würde uns quasi eine Lösung wie bei den Menüs von Wordpress. Das nur als Vergleich.

Übrigens vergeben wir Zahlen von 10 bis 100 an den Seiten, wenn wir schon mal alle in einem Bereich anfassen. Damit wir bei einer neuen Seite parallel zu den anderen nicht _wieder_ alle anderen Seiten öffnen müssen, sondern genügend Spielraum für Ergänzungen im Seitenbaum haben.

**Comment by wrkb** [comment]
Auch das mit den automatischen Pages habe ich nicht verstanden. Alles in Sachen Seitenbaum muss der Admin/Redakteur machen.

**Comment by xwolfde** [comment]
Qautsch was du da schriebst. Wordpress hat dafür die Menüs. Unter Design->Menüs. Die verwendet ihr für allerlei Zeug, nur nicht für Subpages. Das war ganz sicher eine willentliche Entscheidung, die ich offen versuchte nachzudeuten. 
Ihr habt bei den Pages aus welchen Gründen auch immer darauf verzichtet, Menüs zu nutzen. Jetzt müsst ihr damit leben.

**Comment by wrkb** [comment]
Das hatten wir schon vor dem Start des Relaunchs. Die Masse der Menüs wäre unpflegbar (wir reden von Dutzenden), es ist jetzt schon unübersichtlich genug. Komm vorbei und arbeite mal einen Tag mit uns ;)

Man merkt eben, dass Wordpress kein CMS ist.

**Comment by xwolfde** [comment]
Weil ihr das halt so doof gemacht habt, sorry. Ich hätte niemals für jede Subebene ein neues Menü gemacht.  Ich hätte auch nicht mehr Menüs gemacht, sondern das Fakultätsmenü, das hierarchisch weiter oben ist und bereits vorhanden ist nur um Unterebenen erweitert. Die Ebenen, die eben hier auf  Seitenebene auftauchen und wirksam werden. Die Unterebenen werden dann "oben" nur nicht gezeigt.
Das auf das CMS zu schieben ist Unsinn. Das hat nichts mit CMS zu tun, sondern wie man etwas in einem CMS umsetzt.

**Comment by wrkb** [comment]
Wir haben nichts doof gemacht. Wir hatten das Page Tree View, das hat getan, was wir brauchen. Das fiel dann viel später aus nachvollziehbaren Gründen leider weg, um das System nicht zu destabiliseren. Einen Ersatz haben wir aber nicht bekommen. Jetzt rege ich diesen als Enhancement (!) ohne Dringlichkeit an.

Wie soll das Fakultätsmenü helfen? Es geht hier um alle Inhaltsseiten aus https://www.fau.de/sitemap-2/ Die Inhaltsmenüs werden aus dem Seitenbaum automatisch generiert, weil Handarbeit hier Wahnsinn wäre. Ob man die Seiten über ein GEsamtmenü oder viele Einzelnmenüs pflegen würde, ist das dabei eigentlich egal - es ist nicht handhabbar bei mehr als 1000 Seiten (es werden mal 3000).
Das würde nur funktionieren, wenn wir Seiten über die Menü auch im Seitenbaum verorten - also Drag and Drop im Menü-Menü führt zur neuen Anordnung im Seitenbaum. Das habt ihr uns nie vorgeschlagen, sondern nur die Arbeit von Hand.

wäre das mit Menüs verknüpfbar gewesen
